# Generated by Django 5.2.5 on 2025-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailman_service', '0002_alter_mailmanuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmanuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
